// Chiliz Chain Contract Configuration
// Auto-generated by setup-dev.js - DO NOT EDIT MANUALLY

export const CONTRACTS_CONFIG = {
  CAMPAIGN_FACTORY_ADDRESS: '0x8DF4FE6eC4d17c2268293c7AB77711e9330c7EE2',
  PSG_UNWRAPPED_TOKEN: '0xb0Fa395a3386800658B9617F90e834E2CeC76Dd3',
  PSG_WRAPPED_TOKEN: '0x6D124526a5948Cb82BB5B531Bf9989D8aB34C899',
  NETWORK: {
    chainId: 88882,
    name: 'Chiliz Chain',
    rpcUrl: 'https://spicy-rpc.chiliz.com/',
    explorerUrl: 'https://testnet.chiliscan.com',
    faucetUrl: 'https://faucet.chiliz.com'
  }
} as const;

export const CHILIZ_CHAIN_CONFIG = {
  id: 88882,
  name: 'Chiliz Chain',
  network: 'chiliz',
  nativeCurrency: {
    decimals: 18,
    name: 'CHZ',
    symbol: 'CHZ',
  },
  rpcUrls: {
    default: {
      http: ['https://spicy-rpc.chiliz.com/'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Chiliz Scan',
      url: 'https://testnet.chiliscan.com',
    },
  },
} as const;
